// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oklsxdmxmnzenvavhrvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rbHN4ZG14bW56ZW52YXZocnZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNjUzOTYsImV4cCI6MjA2MTc0MTM5Nn0.vI9ssH4sjwOM-JBMAmxlT5M3ba7QBHbOgjdgDQxCgTw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);